# Generated by Django 3.0.7 on 2026-04-13 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_app', '0016_auto_20260411_1915'),
        ('workshop_app', '0016_auto_20260411_0052'),
    ]

    operations = [
    ]
